#!/usr/bin/env ruby
# $Id$

#author: udo waechter (uwaechte@uos.de), 2009-02-14

# NUMHSTCHECKED        number of hosts that have been checked since start.
# NUMHSTSCHEDULED      number of hosts that are currently scheduled to be checked.
# NUMHSTFLAPPING       number of hosts that are currently flapping.
# NUMHSTDOWNTIME       number of hosts that are currently in downtime.
# NUMHSTACTCHKxM       number of hosts actively checked in last 1/5/15/60 minutes.
# NUMHSTPSVCHKxM       number of hosts passively checked in last 1/5/15/60 minutes.
# NUMSVCACTCHKxM       number of services actively checked in last 1/5/15/60 minutes.
# NUMSVCPSVCHKxM       number of services passively checked in last 1/5/15/60 minutes.

checks = ["NUMHSTCHECKED", "NUMHSTSCHEDULED", "NUMHSTFLAPPING", "NUMHSTDOWNTIME",  
               "NUMHSTACTCHK1M", "NUMHSTACTCHK5M", "NUMHSTACTCHK15M", "NUMHSTACTCHK60M",
               "NUMHSTPSVCHK1M", "NUMHSTPSVCHK5M", "NUMHSTPSVCHK15M", "NUMHSTPSVCHK60M", 
               "NUMSVCACTCHK1M", "NUMSVCACTCHK5M", "NUMSVCACTCHK15M", "NUMSVCACTCHK60M", 
               "NUMSVCPSVCHK1M", "NUMSVCPSVCHK5M", "NUMSVCPSVCHK15M", "NUMSVCPSVCHK60M" ].sort
               
checks_join = checks.join(",")               

#config
if ARGV.include?("config")
  puts <<EOM
graph_title Hosts checks by type
graph_category Nagios 
graph_args  --base 1000 -l 0
graph_vlabel Number of checks
EOM
checks.each do |check|
  puts "#{check}.label #{check}"
end  
exit 0
end

out = %x{ /usr/sbin/nagios3stats -m -d #{checks_join} }.split("\n")
cnt = 0
checks.each do |check|
    puts "#{check}.value #{out[cnt]}"
    cnt += 1  
end        
