#!/bin/sh
#author: udo waechter (uwaechte@uos.de), 2008-01-07
#
# show stats about monitored services by nagios
#

#SERVICES=$(nagios2stats --data=NUMSVCOK,NUMSVCWARN,NUMSVCUNKN,NUMSVCCRIT -m |tr \\n \ );
case $1 in
	config)
	cat <<'EOM'
graph_title Services monitored by nagios
graph_category Nagios 
graph_args	--base 1000 -l 0
graph_vlabel nagios_services
SUM.label Total
OK.label OK
WARN.label WARNING
UNKN.label UNKNOWN
CRIT.label CRITICAL
EOM
	exit 0;;
esac

echo -n "SUM.value "
/usr/sbin/nagios3stats --data=NUMSERVICES -m
echo -n "OK.value "
/usr/sbin/nagios3stats --data=NUMSVCOK -m
echo -n "WARN.value "
/usr/sbin/nagios3stats --data=NUMSVCWARN -m
echo -n "UNKN.value "
/usr/sbin/nagios3stats --data=NUMSVCUNKN -m
echo -n "CRIT.value "
/usr/sbin/nagios3stats --data=NUMSVCCRIT -m

