#!/usr/bin/env ruby
#author: udo waechter (uwaechte@uos.de), 2008-01-07
#
# show stats about monitored hosts by nagios
#
# NUMHOSTS
# NUMHSTUP           number of hosts UP.
# NUMHSTDOWN         number of hosts DOWN.
# NUMHSTUNR          number of hosts UNREACHABLE.
# NUMHSTCHECKED        number of hosts that have been checked since start.
# NUMHSTSCHEDULED      number of hosts that are currently scheduled to be checked.
# NUMHSTFLAPPING       number of hosts that are currently flapping.
# NUMHSTDOWNTIME       number of hosts that are currently in downtime.
# NUMHSTACTCHKxM       number of hosts actively checked in last 1/5/15/60 minutes.
# NUMHSTPSVCHKxM       number of hosts passively checked in last 1/5/15/60 minutes.
# NUMSVCACTCHKxM       number of services actively checked in last 1/5/15/60 minutes.
# NUMSVCPSVCHKxM       number of services passively checked in last 1/5/15/60 minutes.
#xxxACTSVCLAT         MIN/MAX/AVG active service check latency (ms).
 #xxxACTSVCEXT         MIN/MAX/AVG active service check execution time (ms).
 #xxxACTSVCPSC         MIN/MAX/AVG active service check % state change.
 #xxxPSVSVCLAT         MIN/MAX/AVG passive service check latency (ms).
 #xxxPSVSVCPSC         MIN/MAX/AVG passive service check % state change.
 #xxxSVCPSC            MIN/MAX/AVG service check % state change.
 #xxxACTHSTLAT         MIN/MAX/AVG active host check latency (ms).
 #xxxACTHSTEXT         MIN/MAX/AVG active host check execution time (ms).
 #xxxACTHSTPSC         MIN/MAX/AVG active host check % state change.
 #xxxPSVHSTLAT         MIN/MAX/AVG passive host check latency (ms).
 #xxxPSVHSTPSC         MIN/MAX/AVG passive host check % state change.
 #xxxHSTPSC            MIN/MAX/AVG host check % state change.
# NUMSERVICES
# NUMSVCOK,
# NUMSVCWARN,
# NUMSVCUNKN,
# NUMSVCCRIT
#xxxACTSVCLAT         MIN/MAX/AVG active service check latency (ms).
 #xxxACTSVCEXT         MIN/MAX/AVG active service check execution time (ms).
 #xxxACTSVCPSC         MIN/MAX/AVG active service check % state change.
 #xxxPSVSVCLAT         MIN/MAX/AVG passive service check latency (ms).
 #xxxPSVSVCPSC         MIN/MAX/AVG passive service check % state change.
 #xxxSVCPSC            MIN/MAX/AVG service check % state change.
 #xxxACTHSTLAT         MIN/MAX/AVG active host check latency (ms).
 #xxxACTHSTEXT         MIN/MAX/AVG active host check execution time (ms).
 #xxxACTHSTPSC         MIN/MAX/AVG active host check % state change.
 #xxxPSVHSTLAT         MIN/MAX/AVG passive host check latency (ms).
 #xxxPSVHSTPSC         MIN/MAX/AVG passive host check % state change.
 #xxxHSTPSC            MIN/MAX/AVG host check % state change.


period = ["MIN","AVG","MAX"]

checks = [] 

["ACTSVCLAT","ACTSVCEXT","PSVSVCLAT", "ACTHSTLAT","ACTHSTEXT",
            "PSVHSTLAT","ACTSVCPSC","PSVSVCPSC","SVCPSC",
            "ACTHSTPSC","PSVHSTPSC","HSTPSC"].sort.each do |chk|
            period.each { |per| checks.push "#{per}#{chk}" }
                end


checks.concat(["NUMSERVICES","NUMSVCOK","NUMSVCWARN","NUMSVCUNKN","NUMSVCCRIT","NUMHSTCHECKED", 
               "NUMHSTSCHEDULED", "NUMHSTFLAPPING", "NUMHSTDOWNTIME",  
               "NUMHSTACTCHK1M", "NUMHSTACTCHK5M", "NUMHSTACTCHK15M", "NUMHSTACTCHK60M",
               "NUMHSTPSVCHK1M", "NUMHSTPSVCHK5M", "NUMHSTPSVCHK15M", "NUMHSTPSVCHK60M", 
               "NUMSVCACTCHK1M", "NUMSVCACTCHK5M", "NUMSVCACTCHK15M", "NUMSVCACTCHK60M", 
               "NUMSVCPSVCHK1M", "NUMSVCPSVCHK5M", "NUMSVCPSVCHK15M", "NUMSVCPSVCHK60M",
               "NUMHOSTS","NUMHSTUP","NUMHSTDOWN","NUMHSTUNR"])

checks.sort!
checks_join = checks.join(",")

out = %x{ /usr/sbin/nagios3stats -m -d #{checks_join} }.split("\n")
cnt = 0
checks.each do |check|
    %x{gmetric --tmax=1800 --name="nagios_#{check}" --value=#{out[cnt]} --type=uint8 --units="Value"}
    cnt += 1  
end   
